### ISSUE TITLE
Display position and not turning off while starting.

### ISSUE THREAD

**Issue by onegladiator4u** [cqjjjzr/MusicBee-DesktopLyrics#6]
Can you fix 3 things brother?
1. Lyric display position changes after musicbee restarts. can you adjust it to remember position when closing. 
2. Even though plugin is closed via view>desktop lyrics it's automatically turn on when musicbee restarts.
3. when there are no synced lyrics it's showing title only. it would be nice to hide if there is no synced lyrics.
Thanks

**Comment by kevye** [comment]
Yes, I had the same issue...The position couldn't be remembered...

Plus, sometimes the lyrics disappeared for no reason, and there was nothing I could do to fix it.
And it might turn on again during the next song. (It was not about the synced lyrics)
Just...pretty randomly...

However, it was a pretty useful plugin. Thanks for making it!

**Comment by cqjjjzr** [comment]
For the first issue, I've already implemented the persistence of the position of the lyrics window. I doubt that it's a DPI-related issue.

For the 2nd issue, I'll contain a fix in the recent patch.

**Comment by cqjjjzr** [comment]
> Plus, sometimes the lyrics disappeared for no reason, and there was nothing I could do to fix it.

I have this issue too, and I didn't managed to debug it out :( sry

**Comment by onegladiator4u** [comment]
Position is still not remembering. it now keep changing position even after turning on `position as is`
But the second issue is fixed when restarting app it won't load lyrics if its not on in view.
Thanks for your work .it is really useful.

**Comment by cqjjjzr** [comment]
closed in https://github.com/cqjjjzr/MusicBee-DesktopLyrics/releases/tag/1.4.0
